services:
  - type: web
    name: airrelay
    runtime: python
    plan: free
    buildCommand: pip install -r api/requirements.txt
    startCommand: python3 run.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: PORT
        value: 10000
      - key: SECRET_KEY
        generateValue: true
